{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clinical-management.fullname" . }}-frontend
  labels:
    {{- include "clinical-management.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "clinical-management.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
