apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clinical-management.fullname" . }}-pdf-pvc
  labels:
    {{- include "clinical-management.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: 5Gi
