spring:
  application:
    name: clinical-management-backend
  
  # PostgreSQL Database - CLEAN SETUP
  datasource:
    url: jdbc:postgresql://localhost:5432/clinical_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: validate  # Use validate with Flyway for schema management
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: false

  # Jackson Configuration for proper date/time serialization
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  # Flyway Migration Configuration
  flyway:
    enabled: true  # Re-enabled for production-ready database management
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0

  # Email Configuration (SMTP)
  mail:
    host: smtp.gmail.com
    port: 587
    username: lebobi35@gmail.com
    password: ppvgbefulrjkroqt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# Management & Monitoring Configuration (Spring Boot Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
    prometheus:
      enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}

# Email sender configuration
email:
  from: lebobi35@gmail.com

server:
  port: 8081

# JWT Configuration
jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  access-token-expiration: 3600000
  refresh-token-expiration: 2592000000

# CORS Configuration
app:
  name: "Clinical Management System"
  cors:
    allowed-origins: "http://localhost:4200,http://127.0.0.1:4200"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
    allowed-headers: "*"
    allow-credentials: true
  
  # Scheduler Configuration
  scheduler:
    # Send appointment reminders daily at 9:00 AM
    reminder-cron: "0 0 9 * * ?"
    # Clean up old appointments every Sunday at midnight
    cleanup-cron: "0 0 0 * * SUN"
    # Mark no-show appointments every hour
    no-show-cron: "0 0 * * * ?"

# Logging
logging:
  level:
    com.clinical.backend: INFO
    root: INFO
