-- NOTE: These are BCrypt hashed passwords for development only
-- Admin password: Admin@123
-- Doctor password: doctor123  
-- Secretary password: secretary123

-- Insert default admin user
-- Hash for 'Admin@123' - Generated by application BCryptPasswordEncoder
INSERT INTO users (email, password_hash, full_name, role, is_active)
VALUES ('admin@clinical.com', '$2a$10$FFkmRDISwxJzdXf6/3WcY.ZpkN8j0Q6rTlTGM593a2V9WruZ6coGq', 'System Administrator', 'ADMIN', true);

-- Insert sample doctor user  
-- Hash for 'doctor123' - Generated by application BCryptPasswordEncoder
INSERT INTO users (email, password_hash, full_name, role, is_active)
VALUES ('doctor@clinical.com', '$2a$10$ugK2MfjtlKqhdPWkva3/1eR6sZ.CDFwgNNLHMKGvo3/Q8B/wCDJ8i', 'Dr. John Smith', 'DOCTOR', true);

-- Insert sample secretary user
-- Hash for 'secretary123' - Generated by application BCryptPasswordEncoder
INSERT INTO users (email, password_hash, full_name, role, is_active)
VALUES ('secretary@clinical.com', '$2a$10$tCvYMXvrHFdwBik2s4E0a.ph442NUAs8N8HCJmHZnD031cHP57NIG', 'Mary Johnson', 'SECRETARY', true);

-- Insert doctor profile
INSERT INTO doctors (user_id, specialty, license_number, phone, room, consultation_fee_cents, available_from, available_to)
SELECT u.id, 'Cardiology', 'MD-12345', '+33123456789', 'A101', 5000, '08:00', '18:00'
FROM users u WHERE u.email = 'doctor@clinical.com';

-- Insert comprehensive sample patients for testing
INSERT INTO patients (first_name, last_name, email, phone, date_of_birth, gender, blood_type, address, emergency_contact_name, emergency_contact_phone, medical_history, allergies)
VALUES 
    ('Alice', 'Dupont', 'alice.dupont@email.com', '+33987654321', '1985-06-15', 'Female', 'O+', '123 Rue de la Paix, 75001 Paris', 'Pierre Dupont', '+33123987456', 'Hypertension since 2015', 'Penicillin'),
    ('Bob', 'Martin', 'bob.martin@email.com', '+33654321987', '1978-03-22', 'Male', 'A+', '456 Avenue des Champs, 75008 Paris', 'Claire Martin', '+33789123456', 'Diabetes Type 2', 'None'),
    ('Catherine', 'Dubois', 'catherine.dubois@email.com', '+33612345678', '1992-11-08', 'Female', 'B+', '789 Boulevard Saint-Germain, 75007 Paris', 'Marc Dubois', '+33687654321', NULL, 'Pollen, Dust'),
    ('David', 'Bernard', 'david.bernard@email.com', '+33698765432', '1965-07-30', 'Male', 'AB+', '321 Rue de Rivoli, 75004 Paris', 'Sophie Bernard', '+33645678901', 'Asthma', 'Aspirin'),
    ('Emma', 'Petit', 'emma.petit@email.com', '+33678901234', '1998-02-14', 'Female', 'O-', '654 Avenue Montaigne, 75008 Paris', 'Louis Petit', '+33634567890', NULL, NULL),
    ('François', 'Richard', 'francois.richard@email.com', '+33656789012', '1982-09-25', 'Male', 'A-', '987 Rue du Faubourg, 75010 Paris', 'Marie Richard', '+33623456789', 'High cholesterol', 'Shellfish'),
    ('Gabrielle', 'Laurent', 'gabrielle.laurent@email.com', '+33634567891', '1975-12-03', 'Female', 'B-', '147 Boulevard Haussmann, 75009 Paris', 'Thomas Laurent', '+33612345679', 'Arthritis', NULL),
    ('Henri', 'Simon', 'henri.simon@email.com', '+33623456780', '1988-04-17', 'Male', 'AB-', '258 Rue de la République, 75011 Paris', 'Julie Simon', '+33601234568', NULL, 'Latex'),
    ('Isabelle', 'Michel', 'isabelle.michel@email.com', '+33612345670', '1970-08-28', 'Female', 'O+', '369 Avenue Victor Hugo, 75016 Paris', 'Paul Michel', '+33690123457', 'Migraine history', 'Ibuprofen'),
    ('Jacques', 'Leroy', 'jacques.leroy@email.com', '+33601234561', '1995-01-19', 'Male', 'A+', '741 Rue de Vaugirard, 75015 Paris', 'Anne Leroy', '+33689012346', NULL, NULL),
    ('Karine', 'Moreau', 'karine.moreau@email.com', '+33690123452', '1983-06-11', 'Female', 'B+', '852 Boulevard Voltaire, 75011 Paris', 'Luc Moreau', '+33678901235', 'Thyroid disorder', 'Seafood'),
    ('Laurent', 'Fournier', 'laurent.fournier@email.com', '+33689012343', '1969-10-05', 'Male', 'O-', '963 Rue Oberkampf, 75011 Paris', 'Sylvie Fournier', '+33667890124', 'Previous heart surgery 2010', NULL),
    ('Marie', 'Girard', 'marie.girard@email.com', '+33678901234', '1991-03-27', 'Female', 'A-', '159 Avenue de la Grande Armée, 75017 Paris', 'Pierre Girard', '+33656789013', NULL, 'Nuts'),
    ('Nicolas', 'Roux', 'nicolas.roux@email.com', '+33667890125', '1987-12-16', 'Male', 'AB+', '357 Rue Lafayette, 75010 Paris', 'Camille Roux', '+33645678902', 'Epilepsy controlled', 'Sulfa drugs'),
    ('Olivia', 'Vincent', 'olivia.vincent@email.com', '+33656789014', '1979-05-09', 'Female', 'B-', '468 Boulevard de Clichy, 75018 Paris', 'Hugo Vincent', '+33634567891', NULL, NULL),
    ('Philippe', 'Muller', 'philippe.muller@email.com', '+33645678903', '1993-09-21', 'Male', 'O+', '579 Rue de Belleville, 75019 Paris', 'Nathalie Muller', '+33623456780', 'Chronic back pain', 'Morphine'),
    ('Quentin', 'Lefebvre', 'quentin.lefebvre@email.com', '+33634567892', '1986-07-13', 'Male', 'A+', '681 Avenue Parmentier, 75011 Paris', 'Isabelle Lefebvre', '+33612345671', NULL, 'Eggs'),
    ('Rachel', 'Mercier', 'rachel.mercier@email.com', '+33623456781', '1996-11-30', 'Female', 'B+', '792 Rue Saint-Antoine, 75004 Paris', 'Daniel Mercier', '+33601234562', 'Previous pregnancy complications', NULL),
    ('Sébastien', 'Blanc', 'sebastien.blanc@email.com', '+33612345672', '1972-02-08', 'Male', 'O-', '814 Boulevard de Strasbourg, 75010 Paris', 'Véronique Blanc', '+33690123453', 'COPD', 'Tobacco smoke'),
    ('Théo', 'Garnier', 'theo.garnier@email.com', '+33601234563', '1999-08-04', 'Male', 'A-', '925 Rue du Temple, 75003 Paris', 'Martine Garnier', '+33689012344', NULL, NULL),
    ('Valérie', 'Faure', 'valerie.faure@email.com', '+33690123454', '1984-04-26', 'Female', 'AB-', '136 Avenue Jean Jaurès, 75019 Paris', 'Olivier Faure', '+33678901236', 'Osteoporosis', 'Dairy products'),
    ('William', 'André', 'william.andre@email.com', '+33689012345', '1977-01-15', 'Male', 'O+', '247 Rue de Charonne, 75011 Paris', 'Céline André', '+33667890125', NULL, NULL),
    ('Xavier', 'Rousseau', 'xavier.rousseau@email.com', '+33678901237', '1990-10-12', 'Male', 'B+', '358 Boulevard Richard Lenoir, 75011 Paris', 'Audrey Rousseau', '+33656789015', 'Depression managed', 'None'),
    ('Yves', 'Boyer', 'yves.boyer@email.com', '+33667890126', '1968-06-19', 'Male', 'A+', '469 Rue Saint-Maur, 75011 Paris', 'Patricia Boyer', '+33645678904', 'Kidney stones history', 'Contrast dye'),
    ('Zoé', 'Henry', 'zoe.henry@email.com', '+33656789016', '1994-12-23', 'Female', 'O-', '571 Avenue de Clichy, 75017 Paris', 'Antoine Henry', '+33634567893', NULL, 'Bee stings');

-- Insert sample appointments for the doctor
INSERT INTO appointments (patient_id, doctor_id, start_time, end_time, status, reason, notes)
SELECT 
    p.id,
    d.id,
    start_time,
    end_time,
    status,
    reason,
    notes
FROM (
    VALUES 
        -- Past appointments (completed/cancelled)
        (1, TIMESTAMP '2024-10-01 09:00:00', TIMESTAMP '2024-10-01 09:30:00', 'COMPLETED', 'Follow-up consultation for hypertension', 'Blood pressure stable, continue medication'),
        (2, TIMESTAMP '2024-10-03 10:00:00', TIMESTAMP '2024-10-03 10:30:00', 'COMPLETED', 'Diabetes check-up', 'A1C levels improved'),
        (3, TIMESTAMP '2024-10-05 14:00:00', TIMESTAMP '2024-10-05 14:30:00', 'CANCELLED', 'Allergy consultation', 'Patient cancelled'),
        (4, TIMESTAMP '2024-10-08 11:00:00', TIMESTAMP '2024-10-08 11:30:00', 'COMPLETED', 'Asthma review', 'Prescribed new inhaler'),
        (5, TIMESTAMP '2024-10-10 15:00:00', TIMESTAMP '2024-10-10 15:30:00', 'NO_SHOW', 'General check-up', 'Patient did not show'),
        (6, TIMESTAMP '2024-10-12 09:30:00', TIMESTAMP '2024-10-12 10:00:00', 'COMPLETED', 'Cholesterol screening', 'Results pending'),
        (7, TIMESTAMP '2024-10-15 13:00:00', TIMESTAMP '2024-10-15 13:30:00', 'COMPLETED', 'Arthritis consultation', 'Adjusted treatment plan'),
        (8, TIMESTAMP '2024-10-17 10:30:00', TIMESTAMP '2024-10-17 11:00:00', 'CANCELLED', 'Skin rash evaluation', 'Doctor unavailable'),
        (9, TIMESTAMP '2024-10-20 14:30:00', TIMESTAMP '2024-10-20 15:00:00', 'COMPLETED', 'Migraine follow-up', 'Medication effective'),
        (10, TIMESTAMP '2024-10-22 11:30:00', TIMESTAMP '2024-10-22 12:00:00', 'COMPLETED', 'Annual physical exam', 'All vitals normal'),
        
        -- Recent appointments
        (11, TIMESTAMP '2024-10-25 09:00:00', TIMESTAMP '2024-10-25 09:30:00', 'COMPLETED', 'Thyroid disorder check', 'Labs ordered'),
        (12, TIMESTAMP '2024-10-27 15:00:00', TIMESTAMP '2024-10-27 15:30:00', 'COMPLETED', 'Post-surgery follow-up', 'Healing well'),
        
        -- Upcoming appointments (scheduled/confirmed)
        (13, TIMESTAMP '2024-11-02 09:00:00', TIMESTAMP '2024-11-02 09:30:00', 'CONFIRMED', 'Nut allergy consultation', NULL),
        (14, TIMESTAMP '2024-11-04 10:00:00', TIMESTAMP '2024-11-04 10:30:00', 'SCHEDULED', 'Epilepsy medication review', NULL),
        (15, TIMESTAMP '2024-11-06 11:00:00', TIMESTAMP '2024-11-06 11:30:00', 'CONFIRMED', 'General health assessment', NULL),
        (16, TIMESTAMP '2024-11-08 14:00:00', TIMESTAMP '2024-11-08 14:30:00', 'SCHEDULED', 'Back pain consultation', NULL),
        (17, TIMESTAMP '2024-11-10 09:30:00', TIMESTAMP '2024-11-10 10:00:00', 'CONFIRMED', 'Egg allergy testing', NULL),
        (18, TIMESTAMP '2024-11-12 13:00:00', TIMESTAMP '2024-11-12 13:30:00', 'SCHEDULED', 'Prenatal check-up', NULL),
        (19, TIMESTAMP '2024-11-15 10:30:00', TIMESTAMP '2024-11-15 11:00:00', 'CONFIRMED', 'COPD management', NULL),
        (20, TIMESTAMP '2024-11-18 15:00:00', TIMESTAMP '2024-11-18 15:30:00', 'SCHEDULED', 'Sports physical', NULL),
        (21, TIMESTAMP '2024-11-20 09:00:00', TIMESTAMP '2024-11-20 09:30:00', 'CONFIRMED', 'Osteoporosis screening', NULL),
        (22, TIMESTAMP '2024-11-22 11:30:00', TIMESTAMP '2024-11-22 12:00:00', 'SCHEDULED', 'Routine check-up', NULL),
        (23, TIMESTAMP '2024-11-25 14:00:00', TIMESTAMP '2024-11-25 14:30:00', 'CONFIRMED', 'Depression follow-up', NULL),
        (24, TIMESTAMP '2024-11-27 10:00:00', TIMESTAMP '2024-11-27 10:30:00', 'SCHEDULED', 'Kidney stone prevention', NULL),
        (25, TIMESTAMP '2024-11-29 13:30:00', TIMESTAMP '2024-11-29 14:00:00', 'CONFIRMED', 'Allergy shot', NULL)
) AS t(patient_id, start_time, end_time, status, reason, notes)
CROSS JOIN (SELECT id FROM patients LIMIT 1) p
CROSS JOIN (SELECT id FROM doctors LIMIT 1) d
WHERE t.patient_id <= (SELECT COUNT(*) FROM patients);
